# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cryptoparty Ann Arbor
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Party like it's 1984.

  Cryptoparty Ann Arbor is a group of privacy-minded educators,
  techies, and enthusiasts. We're here to help you keep your privacy
  in the modern age.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a2crypto.party" # the base hostname & protocol for your site
twitter_username: CryptopartyAA
github_username:  Cryptoparty-Ann-Arbor

# Build settings
markdown: kramdown
